TARGET = arduino

C_FILES = \
	lib/main.c \
	lib/gpio.c \
	lib/ticker.c \
	lib/uart.c \
	lib/spi.c \
	lib/eeprom.c \
	lib/i2cmaster.c \
	lib/pinterrupt.c \
	../common/buffer.c \
	../common/utility.c \
	sketch.c

pre-flash:
	

include Makefile.include
